### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mjebrahimi** [mehdihadeli/awesome-dotnet-architecture#1]
The [**CC0 1.0 Universal (CC0 1.0)**](https://creativecommons.org/publicdomain/zero/1.0/) license is commonly used for awesome repositories.

For example, see this [LICENSE](https://github.com/mjebrahimi/Awesome-Microservices-NetCore/blob/master/LICENSE) and [license section](https://github.com/mjebrahimi/Awesome-Microservices-NetCore/blob/master/README.md#L533)

**Comment by mehdihadeli** [comment]
@mjebrahimi Thanks
